import os

Import("env daemon")

tests = env.Glob("test_*.py")

env['GRPCDEFSDIR'] = env.Dir(os.path.join("#", "src", "rpc_defs"))
env['GRPCOUTDIR'] = env.Dir(".")
env['GRPCPYTHONOUTDIR'] = '$GRPCOUTDIR'
env['GRPCSOURCE'] = 'filewatch.proto'
env['TESTRUNNER'] = env.File('run_tests.py')

testresult = env.Command("daemon_report.txt", [daemon] + tests,
                         [
                             "python3 -m grpc_tools.protoc -I$GRPCDEFSDIR --python_out=$GRPCOUTDIR --grpc_python_out=$GRPCPYTHONOUTDIR $GRPCDEFSDIR/$GRPCSOURCE",
                             "python3 $TESTRUNNER $SOURCES --tee-output $TARGET"
                         ])

env.Depends(testresult, "run_tests.py")

Return("testresult")
