import os

Import('env')

grpc_protoc_cmd = "protoc -I %s --grpc_out=%s --plugin=protoc-gen-grpc=`which grpc_cpp_plugin` $SOURCE"
protoc_cmd = "protoc -I %s --cpp_out=%s $SOURCE"
env.Command([env.File(os.path.join("generated", "filewatch.grpc.pb.cc")),
             env.File(os.path.join("generated", "filewatch.grpc.pb.h")),
             env.File(os.path.join("generated", "filewatch.pb.cc")),
             env.File(os.path.join("generated", "filewatch.pb.h"))],
            env.File("filewatch.proto"),
            [
                Mkdir(env.Dir("generated")),
                grpc_protoc_cmd % (env.Dir(".").path, env.Dir("generated").path),
                protoc_cmd % (env.Dir(".").path, env.Dir("generated").path)
            ])

rpclib = env.StaticLibrary("filewatch_rpc", env.Glob(os.path.join("generated", "*.cc")))

Return('rpclib')
